In [ ]:
from IPython import display
import numpy as np
import random
import torch
from torch import nn
from torch import optim

In [ ]:
x = torch.FloatTensor(3, 4, 5)

In [ ]:
x.shape

torch.Size([3, 4, 5])

In [ ]:
x

tensor([[[0.0000e+00, 0.0000e+00, 5.9163e-38, 3.1185e-30, 1.6563e-37],
         [0.0000e+00, 1.6563e-37, 0.0000e+00, 3.1069e-30, 5.5102e-39],
         [4.1359e-24, 2.6808e-36, 1.6563e-37, 0.0000e+00, 1.6563e-37],
         [0.0000e+00, 1.2430e-29, 2.6803e-36, 1.0721e-35, 2.2967e-39]],

        [[9.2420e-41, 7.6239e-39, 6.4864e+19, 6.1630e-33, 1.3563e-19],
         [1.3563e-19, 1.1431e+27, 3.2531e+33, 2.0193e-19, 1.9432e-19],
         [1.9445e+31, 7.3387e+28, 2.0617e-19, 1.8320e+25, 1.8493e+20],
         [1.7442e+28, 7.0964e+22, 1.8465e+25, 8.3986e-33, 1.3563e-19]],

        [[1.3563e-19, 2.8670e+32, 1.8527e+28, 1.8470e+31, 6.8608e+22],
         [3.0351e+32, 7.3970e+20, 7.5655e+28, 3.0186e+32, 4.5434e+30],
         [1.1692e-19, 1.3563e-19, 1.4222e-13, 1.5771e-19, 3.4063e+12],
         [1.3563e-19, 1.3563e-19, 9.3228e-09, 8.4020e+05, 3.2683e+03]]])

In [ ]:
y = x.view(4 * 5 * 3)

In [ ]:
y

tensor([0.0000e+00, 0.0000e+00, 5.9163e-38, 3.1185e-30, 1.6563e-37, 0.0000e+00,
        1.6563e-37, 0.0000e+00, 3.1069e-30, 5.5102e-39, 4.1359e-24, 2.6808e-36,
        1.6563e-37, 0.0000e+00, 1.6563e-37, 0.0000e+00, 1.2430e-29, 2.6803e-36,
        1.0721e-35, 2.2967e-39, 9.2420e-41, 7.6239e-39, 6.4864e+19, 6.1630e-33,
        1.3563e-19, 1.3563e-19, 1.1431e+27, 3.2531e+33, 2.0193e-19, 1.9432e-19,
        1.9445e+31, 7.3387e+28, 2.0617e-19, 1.8320e+25, 1.8493e+20, 1.7442e+28,
        7.0964e+22, 1.8465e+25, 8.3986e-33, 1.3563e-19, 1.3563e-19, 2.8670e+32,
        1.8527e+28, 1.8470e+31, 6.8608e+22, 3.0351e+32, 7.3970e+20, 7.5655e+28,
        3.0186e+32, 4.5434e+30, 1.1692e-19, 1.3563e-19, 1.4222e-13, 1.5771e-19,
        3.4063e+12, 1.3563e-19, 1.3563e-19, 9.3228e-09, 8.4020e+05, 3.2683e+03])

In [ ]:
z = y.reshape(6, 10)

In [ ]:
z

tensor([[0.0000e+00, 0.0000e+00, 5.9163e-38, 3.1185e-30, 1.6563e-37, 0.0000e+00,
         1.6563e-37, 0.0000e+00, 3.1069e-30, 5.5102e-39],
        [4.1359e-24, 2.6808e-36, 1.6563e-37, 0.0000e+00, 1.6563e-37, 0.0000e+00,
         1.2430e-29, 2.6803e-36, 1.0721e-35, 2.2967e-39],
        [9.2420e-41, 7.6239e-39, 6.4864e+19, 6.1630e-33, 1.3563e-19, 1.3563e-19,
         1.1431e+27, 3.2531e+33, 2.0193e-19, 1.9432e-19],
        [1.9445e+31, 7.3387e+28, 2.0617e-19, 1.8320e+25, 1.8493e+20, 1.7442e+28,
         7.0964e+22, 1.8465e+25, 8.3986e-33, 1.3563e-19],
        [1.3563e-19, 2.8670e+32, 1.8527e+28, 1.8470e+31, 6.8608e+22, 3.0351e+32,
         7.3970e+20, 7.5655e+28, 3.0186e+32, 4.5434e+30],
        [1.1692e-19, 1.3563e-19, 1.4222e-13, 1.5771e-19, 3.4063e+12, 1.3563e-19,
         1.3563e-19, 9.3228e-09, 8.4020e+05, 3.2683e+03]])

In [ ]:
a = torch.IntTensor(10)

In [ ]:
a

tensor([88453568,        0, 16843009,    65537, 16843009, 16843009, 16843009,
        16843009, 16843009, 16843009], dtype=torch.int32)

In [ ]:
b = z * a

In [ ]:
b

tensor([[0.0000e+00, 0.0000e+00, 9.9647e-31, 2.0438e-25, 2.7897e-30, 0.0000e+00,
         2.7897e-30, 0.0000e+00, 5.2330e-23, 9.2808e-32],
        [3.6584e-16, 0.0000e+00, 2.7897e-30, 0.0000e+00, 2.7897e-30, 0.0000e+00,
         2.0935e-22, 4.5145e-29, 1.8057e-28, 3.8684e-32],
        [8.1749e-33, 0.0000e+00, 1.0925e+27, 4.0390e-28, 2.2845e-12, 2.2844e-12,
         1.9253e+34,        inf, 3.4011e-12, 3.2729e-12],
        [       inf, 0.0000e+00, 3.4725e-12, 1.2006e+30, 3.1148e+27, 2.9378e+35,
         1.1952e+30, 3.1100e+32, 1.4146e-25, 2.2844e-12],
        [1.1997e-11, 0.0000e+00, 3.1205e+35, 1.2105e+36, 1.1556e+30,        inf,
         1.2459e+28, 1.2743e+36,        inf, 7.6525e+37],
        [1.0342e-11, 0.0000e+00, 2.3954e-06, 1.0336e-14, 5.7372e+19, 2.2844e-12,
         2.2844e-12, 1.5702e-01, 1.4151e+13, 5.5047e+10]])

In [ ]:
c = b @ b.reshape(10,6)
c

tensor([[       nan, 4.0045e+15, 5.3709e+04,        nan, 2.2329e+02, 5.1088e-21],
        [       nan, 7.8982e+10, 5.3761e+04,        inf, 5.6245e-01, 5.7526e+07],
        [       inf,        inf,        inf,        inf,        inf,        inf],
        [       nan,        nan,        inf,        inf,        inf,        nan],
        [       inf,        nan,        inf,        nan,        inf,        inf],
        [       inf,        inf,        inf,        inf, 1.9571e+27, 2.0009e+35]])

In [ ]:
from scipy.misc import derivative

def foo(x, z, t):
  return(x**3 + z - 75*t)

def partial_derivative(func, var=0, point=[]):
    args = point[:]
    def wraps(x):
        args[var] = x
        return func(*args)
    return derivative(wraps, point[var], dx = 1e-6)

partial_derivative(foo, var=0, point= [1, 0.5, 2])

3.000000006636583

In [ ]:
e  = torch.eye(5, 6)
e

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

In [ ]:
e.numpy()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)